### ISSUE TITLE
new __load__

### ISSUE THREAD

**Issue by hakehuang** [hakehuang/yml_merger#1]
```
__load__: 
  - test_new_load_branch.yml: [a, d]

project:
  __add__:
    - a
  configuration:
    section-type: application
  node_root:
    __add__:
      - d 
    src:
      - path: test.c
        rootdir: project_root
 
```
test_new_load_branch.yml
```
a:
  node_root:
    branch_a: "I am from branch a"

b: 
  src: 
    - path: b.c
      rootdir: "branch b"

c:
  node_root:
    branch_c: "I am from branch c"

d: 
  src: 
    - path: d.c
      rootdir: "branch d"

```

the merged result shall be as below

```
project:
  __add__:
  - a
  configuration:
    section-type: application
  node_root:
    __add__:
    - d
    src:
    - path: test.c
      rootdir: project_root
a:
  node_root:
    branch_a: I am from branch a
  attribute: required
d:
  src:
  - path: d.c
    rootdir: branch d

```
